# Generated by Django 6.1 on 2026-08-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="Укажите город",
                max_length=30,
                null=True,
                verbose_name="Город",
            ),
        ),
    ]
