# Generated by Django 6.1 on 2026-09-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.PositiveIntegerField(verbose_name="Сумма оплаты"),
        ),
    ]
