# Generated by Django 6.1 on 2026-09-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_payment_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.CharField(
                blank=True, max_length=400, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID сессии"
            ),
        ),
    ]
