# Generated by Django 6.1 on 2026-09-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment_link_payment_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="link",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
    ]
